### ISSUE TITLE
UA Перевод

### ISSUE THREAD

**Issue by kotleni** [PetruCHIOrus/lead_ind#13]
**бурь** ? может **бур**?

**Comment by PetruCHIOrus** [comment]
ахах это автопереводчик видимо, если б @prosta4okua переводил, то он бы этого не допустил

**Comment by kotleni** [comment]
Бывает, **могу помочь с переводом на UA**

**Comment by Prosta4okua** [comment]
> Бывает, **могу помочь с переводом на UA**

Гайда! Я виправлю помилки.

**Comment by kotleni** [comment]
Ок.

**Comment by skykatik** [comment]
Рофл вышел из-под рофла)
