### ISSUE TITLE
Apple tablet no resource 

### ISSUE THREAD

**Issue by Jericho0717** [PetruCHIOrus/lead_ind#14]
No new resource come up on map

**Comment by PetruCHIOrus** [comment]
I know. To be honest, while I have no desire to finish the mod, and besides, specifically at this time I have studies, practice, a course project and other joys
(sorry fo machine translate)

**Comment by Jericho0717** [comment]
Will it work better on pc?

**Comment by PetruCHIOrus** [comment]
> Will it work better on pc?

equally

**Comment by Jericho0717** [comment]
> > Will it work better on pc?
> 
> equally

You mean it will have the same problem

**Comment by PetruCHIOrus** [comment]
> > > Will it work better on pc?
> > 
> > 
> > equally
> 
> You mean it will have the same problem

Mod has no maps for company, I'm lost the desire to make a mod and the second developer may continue

**Comment by Jericho0717** [comment]
If you ever do you have a great mind for bettering the game and thank you for what you have created
