### ISSUE TITLE
[Suggestion] New Turret

### ISSUE THREAD

**Issue by WilloIzCitron** [PetruCHIOrus/lead_ind#17]
I Maded a new turret but its unnamed but i send a sprite
![](https://cdn.discordapp.com/attachments/656612099128164362/781333767708475452/Turret1.png)

Thank You

**Comment by PetruCHIOrus** [comment]
I didn't answer that for some reason, but in general I don't mind such a new gun, thank you
I'll leave the issue open so I don't forget if I add it
