### ISSUE TITLE
Various issues (might just be mobile)

### ISSUE THREAD

**Issue by jhrushbe** [PetruCHIOrus/lead_ind#19]
The heatdrill and plutonium reactor have "oh no"
Units cannot be built
Turrets and universal storage do not renter correctly, and the turrets cannot shoot

**Comment by PetruCHIOrus** [comment]
maybe fixed?

**Comment by PetruCHIOrus** [comment]
ok, update published and maybe @paulieg626 already fixed all problems (ex. sounds), if no - create new issue
