### ISSUE TITLE
add mod in github error

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [PetruCHIOrus/lead_ind#24]
![Screenshot_20210117_150544_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/67987607/104833692-8f46eb00-58d5-11eb-99b5-b5c8b55f8e19.jpg)

**Comment by PetruCHIOrus** [comment]
strange, but now i successfully imported mod
![Screenshot_20210117-200742_Mindustry 1](https://user-images.githubusercontent.com/39710644/104850473-5ff9a380-5900-11eb-94fa-6bd82a4bc8b3.png)
Maybe now works?
If no, try download release from releases tab or use vpn. It's China? Maybe really github needs vpn 🤔

**Comment by Mr-Ao-Dragon** [comment]
when i opened VPN![Screenshot_20210131_122459_io.anuke.mindustry.jpg](https://user-images.githubusercontent.com/67987607/106374582-9be03e80-63bf-11eb-9128-c77d1f359fbb.jpg)
yep, i chinese
![Screenshot_20210131_122611_com.autonavi.minimap.jpg](https://user-images.githubusercontent.com/67987607/106374594-bb776700-63bf-11eb-8541-a39acb88a77b.jpg)
